### ISSUE TITLE
Levee Moving Window Sort Error

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#779]
Levee ideas.

- [x] Modify the moving window code to clip the levee lines to the window using a temp layer prior to running the levee calculator.
- [x] There are two processes that check duplicates.  This is not correct.  One checks for duplicates and one checks for redundant levees.  Rename the processes correctly.
- [ ] The duplicate levee check needs to be added to walls failure.
- [x] Add a method to calculate levee height from grid based on the correction field.  This will eliminate walls that are underground.
- [ ] Build a test project for small tests and large tests.

**Comment by FLO-2DKaren** [comment]
Test on Metro.

**Comment by FLO-2DKaren** [comment]
Wall height vs Crest Elevation
Calc wall height from grid and correction field

**Comment by FLO-2DKaren** [comment]
Test 3D import method.

**Comment by FLO-2DKaren** [comment]
Failure images from Elizabeth.
![image](https://user-images.githubusercontent.com/20424460/161118107-32053303-2d71-4695-85ed-98b03b6f7f4a.png)

![image](https://user-images.githubusercontent.com/20424460/161118160-a05c2de3-a442-4836-a8db-59721a20b174.png)

**Comment by saberraz** [comment]
Needs further discussions to better understand the requirements.

**Comment by FLO-2DKaren** [comment]
@vcloarec 
Hi Vincent,
This project is the exact one I sent for Infiltration.  So if you already downloaded it, you can ignore this link.
https://flo-2d.sharefile.com/d-sa6587132e03a47468135d6806b92e7f6

The current wall / levee instructions are here:
https://documentation.flo-2d.com/Workshops/Lesson%204.html#step-3-assign-walls

The wall data is in the first link.

**Comment by vcloarec** [comment]
> Moving window code does this...
> 
> Makes a window of 100 x 100 grid elements 10,000 cell areas per window Isolates the data and only analyze grids inside the window. (I'm not certain this is accurate.) Progress bar tells you how many windows are finished.
> 
> If a line crosses a window, it is copied into a duplicate Levee Line (user layer). (I think we can use a clipping tool instead)

If I understand well, here, it is when user import the levee line from the "Wall" vector layer. So it is just a copy of the feature from the "Wall" vector layer to the "Levee" user layer, with the copy attributes values from Wall fields to Levee fields.
In that case, I think it is is useless to use the moving windows algorithm, there is no gain to use it here. Moreover, this add a level of complexity (the duplicate levee lines). It would be better to implement a more direct copy, that will fix some issues.

Do you want I replace the window moving window approach by a direct copy?

**Comment by FLO-2DKaren** [comment]
@vcloarec 

I think it should only be in the schematize part but maybe run an index before the copy because there are lots of lines to copy on a big project.

**Comment by vcloarec** [comment]
@FLO-2DKaren 
#818 could fixes some issues described here, but do not fill all the requirements described here. That why I wrote "work in progress" (WIP).

**Comment by FLO-2DKaren** [comment]
@vcloarec 
Okay Dokie.  

I will be testing Storm drain and Mult chan stuff this weekend.  I'll also be updating documentation.  I wasn't planning to test your stuff but I did merge it simply to see if it causes any issues during my other testing.

I hope to have everything wrapped up by June 1 so the District has 1 month to do their own validation stuff.

I won't be processing a release until then but I'm merging until you tell me not to because it's easier for me to have it all in one plugin.  I get confused when testing multiple plugins and it's frustrating.  So if you don't want something merged, note that in a comment and I'll hold off.

**Comment by FLO-2DKaren** [comment]
The merge closed this so I'll just reopen it.

**Comment by vcloarec** [comment]
> Wall height vs Crest Elevation for Walls only Calc wall height from grid and correction field.
> 
> Note:: This code is already in the Wall Failure Calc code. Apply it to the Calculate Levee code by assessing the cell elevation and adding the correction field to the grid element elevation as a final wall elevation.
> 
> The end user adds the wall height to the correction field.
> 
> Need a way to Identify that the height is being used instead of the crest elevation
> 
> The wall elevation will be calculated instead of copied from the levee line.

Looking at the code, and it seems (not tested) that the current behavior is the one described above, but maybe I have misunderstood.
Regarding to the levee line user layer, the current behavior is:
- if there is a value in "elev" and **no** value in "correction": the crest elevation is "elev"
- if there is a value in "elev" and a value in "correction", the crest elevation is "elev" + "correction"
- if there is **no** value in "elev" and a value in "correction, the crest elevation is grid_elevation + "correction"
- if there **no** value in "elev" and **no* value in correction, the crest elevation is grid_elevation
```

//  elev   //  correction //    crest elevation  
-----------------------------------------------------
//   X     //     Null   //      elev
//   X     //     X      //      elev + correction
//  Null   //     X      //      grid elevation + correction
//  Null   //     Null   //      grid elevation

```

So with this current behavior, for wall, if the user set the "correction" field to the wall height, you will have the behavior you want, no?
Tell me if I miss something.

**Comment by FLO-2DKaren** [comment]
@vcloarec 

Hi Vincent

So I want the wall to be like number 3 in your table.  Wall crest will be NULL and the Correction will be a height.  But the crest elevation will be the highest grid elevation + correction.  That is the difference.  Highest grid elevation is the max of the elevation on either side of the levee.  It is based on the cell on either side of the red levee line.  That's where the wall failure code comes into play because it already uses that algorithm.

**Comment by vcloarec** [comment]
@FLO-2DKaren , ok I got it.
Other question: do you want this behavior only for wall or for all levee? If first, it seems to me more difficult.

**Comment by FLO-2DKaren** [comment]
@vcloarec 
All levees please.  I don't think isolating the walls will be necessary.  I'll just modify the instructions so it's clear there.

**Comment by vcloarec** [comment]
> The duplicate levee check needs to be added to walls failure.

@FLO-2DKaren , can you clarify this point?

**Comment by FLO-2DKaren** [comment]
@vcloarec 

Thanks for asking.  We didn't discuss this in our meeting because I forgot about it and missed it on the list.  Look at the levee.dat file export.  The L line used to have duplicate D lines under them but we added code to take them out.  I believe that  I identified the code a few comments up.  I just want you to apply the same Duplicate removal to the W lines that are under the F lines.

L D represent levees and F W represent failure.

L  34117
D  6  1440.205
D  3  1440.205
D  7  1440.205

F  34117
W  6  1440.0386  0.0  0.0  0.0  0.0  0.0
W  3  1440.7239  0.0  0.0  0.0  0.0  0.0
W  7  1440.4429  0.0  0.0  0.0  0.0  0.0
W  6  1440.0386  0.0  0.0  0.0  0.0  0.0
W  3  1440.7239  0.0  0.0  0.0  0.0  0.0
W  7  1440.4429  0.0  0.0  0.0  0.0  0.0

**Comment by vcloarec** [comment]
@FLO-2DKaren , I can't reproduce this issue with the project that you had shared with me.

**Comment by FLO-2DKaren** [comment]
@vcloarec I shared 2 projects with you.  One has Walls and the other one doesn’t.  It should be the one with the walls.

**Comment by vcloarec** [comment]
@FLO-2DKaren , hmmm, the one with the walls works fine. But this one has only 4481 grid cells, and the results you expose has a grid number of 34117, so maybe not the same.

**Comment by FLO-2DKaren** [comment]
I’m on that meeting if you want to look at it together.

https://global.gotomeeting.com/join/588412037

**Comment by FLO-2DKaren** [comment]
@vcloarec If you clipped the levee lines, you might have fixed it a different way.   It may not have as many levees calculated.  In that case, I'll just need to vigorously test it to make sure the wall  calculations are good.

**Comment by vcloarec** [comment]
> you might have fixed it a different way.

yes, It was also my though...

**Comment by vcloarec** [comment]
> I’m on that meeting if you want to look at it together. https://global.gotomeeting.com/join/588412037

I am not available for meeting now...

**Comment by FLO-2DKaren** [comment]
@vcloarec 
Vincent, I'm testing the levees but I don't think the crest elevation is working correctly.  Did you merge the code that applied the wall elevation from the grid + correction?

**Comment by vcloarec** [comment]
it works on my side, can you share your project and tell me where is the problem?

**Comment by FLO-2DKaren** [comment]
Here's what I'm applying in the Calculate Walls to Levees 
![image](https://user-images.githubusercontent.com/20424460/167698405-6b86c0ef-b131-4f61-8a1f-c566856eed33.png)

**Comment by vcloarec** [comment]
@FLO-2DKaren , indeed ! fixed by https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/825

**Comment by FLO-2DKaren** [comment]
@vcloarec 

Hi Vincent,

I just got the new code and resumed testing.  The levee fail duplicate error is still happening.  Can you look at the code that removes the duplicates from the Schematic/Levees table and apply it to the Levee Failure Table.

![image](https://user-images.githubusercontent.com/20424460/167841005-d858dd3c-9904-4b90-b52e-547587e13894.png)

**Comment by vcloarec** [comment]
@FLO-2DKaren , very sorry but I can't reproduce the duplicate levee failure, and I don't see any reason for these duplicate. I am using the project you gave me here:https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/779#issuecomment-1109992388

**Comment by FLO-2DKaren** [comment]
@vcloarec 

Can you please try this?  Run a field statistic on the Levee Failure Table and then see if the Majority value has more than 3 or 4 listings in the ifaildir field.

![image](https://user-images.githubusercontent.com/20424460/167860347-d24a31cb-49d9-42f5-80d2-ff80d257335f.png)

**My cell size is 30**.  Make sure your cell size is 30 too.  I just noticed that one of my projects was accidentally using 100ft as the cell size.

I'm fairly confident that this test is failing because I have emptied out those tables completely to recalculate the levees.

**Comment by FLO-2DKaren** [comment]
[Wall Failure Duplicate Project.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/8670321/Wall.Failure.Duplicate.Project.zip)

@vcloarec Here's my project.

**Comment by vcloarec** [comment]
@FLO-2DKaren this should fix the duplicate: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/826

**Comment by FLO-2DKaren** [comment]
@vcloarec 
Hi Vincent,
Can you please check one more thing for me?  I think we are getting really close.  I am not getting the WallHeight to be assigned to the correction field when I add walls to the levee lines.

![image](https://user-images.githubusercontent.com/20424460/168138575-4ca91827-53cb-4371-99b2-33d23cb5d7a2.png)

![image](https://user-images.githubusercontent.com/20424460/168138718-5158ab49-311b-424a-8330-e86034f64677.png)

**Comment by FLO-2DKaren** [comment]
[Walls.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/8681549/Walls.zip)
Here's the shapefile I'm using.

**Comment by FLO-2DKaren** [comment]
All OK in QGIS 3.22.  Tested on Big Wall Test.
https://flo-2d.sharefile.com/d-s44b21a037b304940b9304713920a54f4

**Comment by vcloarec** [comment]
> I found a weird issue while testing the wall elevation import.

Indeed, I didn't see this issue that existed before my work. Should be fixed by https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/830
