### ISSUE TITLE
Mult Chan Geometric Predicate

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#816]
@FLO-2DJJ 

JJ can you please correct the geometric predicate on the intersection.

The geometric predicate that intersects the grid layer to the polyline layers is probably set to touch or intersect.  We need to use a method where the line crosses the grid.

Here is what we are currently getting when a line touches a corner but doesn't cross a grid.
![image](https://user-images.githubusercontent.com/20424460/159184990-fe141ed1-7d7f-4b02-8b50-eab9b48b9cf9.png)

We should be writing this:
![image](https://user-images.githubusercontent.com/20424460/159185015-8139a6f4-8906-4b9d-bc71-3afecc2c72b2.png)

Here is an example of a spatial join that uses the correct geometric predicate.

![image](https://user-images.githubusercontent.com/20424460/159185053-8228be16-30f1-4943-a14f-96fc33cfb355.png)

**Comment by FLO-2DJJ** [comment]
Ok. Got it. Will do it.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren , I merged commits to the master plugin that uses the ST_Crosses predicate (instead of ST_Intersects) in triggers (in db_structure.sql)  that creates the cells that intersects (now crosses) the multiple channels and simple multiple channels.
See:
....ST_Crosses(CastAutomagic(g.geom), CastAutomagic(NEW.geom))

To test it you need to create a new project with the new database definitions.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Hi JJ,  This is still broken because the update code isn't correct.  Both mult and simple mult probably need fixed.

`CREATE TRIGGER IF NOT EXISTS "find_cells_mult_line_insert"
    AFTER INSERT ON "mult_lines"
    WHEN (SELECT enabled FROM trigger_control WHERE name = 'find_cells_mult_line_insert') AND (NEW."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom"))
    BEGIN
        DELETE FROM "mult_cells" WHERE line_fid = NEW."fid";
        INSERT INTO "mult_cells" (line_fid, grid_fid, wdr, dm, nodchns, xnmult)
            SELECT NEW.fid, g.fid, NEW.wdr, NEW.dm, NEW.nodchns, NEW.xnmult  FROM grid as g
            WHERE ST_Crosses(CastAutomagic(g.geom), CastAutomagic(NEW.geom));
    END;


INSERT INTO trigger_control (name, enabled) VALUES ('find_cells_mult_line_update', 1);
CREATE TRIGGER IF NOT EXISTS "find_cells_mult_line_update"
    AFTER UPDATE ON "mult_lines"
    WHEN (SELECT enabled FROM trigger_control WHERE name = 'find_cells_mult_line_update') AND (NEW."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom"))
    BEGIN
        DELETE FROM "mult_cells" WHERE line_fid = OLD."fid";
        INSERT INTO "mult_cells" (line_fid, grid_fid, wdr, dm, nodchns, xnmult)
        SELECT NEW.fid, g.fid, NEW.wdr, NEW.dm, NEW.nodchns, NEW.xnmult FROM grid as g
        WHERE ST_Crosses(CastAutomagic(g.geom), CastAutomagic(NEW.geom));
    END;`

- [ ] Add ST_Crosses to the update code.
- [ ] The update code only applies to added lines not modified lines.  See the Delete From.  It only applies new features and ignores old features.

**Comment by FLO-2DJJ** [comment]
I'll look into it.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren I modified the plugin to use ST_Crosses in updates to polylines of mult channels and simple mult channels. See if that solves the issue. Not sure about your comment about old or new features. I thinks it applies to both. Please check it.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ I think there will still be a problem because you are only updating New Polylines and not all polylines.

Can you change the code so that it applies to All features and not just the features with a new FID?  Because now if I move a node, on an old line, it won't update that line because the FID is old.

![image](https://user-images.githubusercontent.com/20424460/169655124-d7da8efb-1c47-4849-b005-6bcb0471e387.png)

**Comment by FLO-2DJJ** [comment]
Ok Karen, I'll look at it.
Do you think we should also use the ST_Crosses predicate for polygons?

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Is that a different issue?  You mean the other polygon intersection code?   I think it depends on the situation.  I'll make a new issue and we can study it.

**Comment by FLO-2DJJ** [comment]
I mean the areas (polygons) that define the features for the Multiple
Channels Areas:

[image: image.png]

They use ST_Intersects:

INSERT INTO trigger_control (name, enabled) VALUES
('find_cells_mult_insert', 1);
CREATE TRIGGER IF NOT EXISTS "find_cells_mult_insert"
    AFTER INSERT ON "mult_areas"
    WHEN (SELECT enabled FROM trigger_control WHERE name =
'find_cells_mult_insert') AND (NEW."geom" NOT NULL AND NOT
ST_IsEmpty(NEW."geom"))
    BEGIN
        DELETE FROM "mult_cells" WHERE area_fid = NEW."fid";
        INSERT INTO "mult_cells" (area_fid, grid_fid, wdr, dm, nodchns,
xnmult)
            SELECT NEW.fid, g.fid, NEW.wdr, NEW.dm, NEW.nodchns, NEW.
xnmult  FROM grid as g
            WHERE ST_Intersects(CastAutomagic(g.geom),
CastAutomagic(NEW.geom));
    END;

INSERT INTO trigger_control (name, enabled) VALUES
('find_cells_mult_update', 1);
CREATE TRIGGER IF NOT EXISTS "find_cells_mult_update"
    AFTER UPDATE ON "mult_areas"
    WHEN (SELECT enabled FROM trigger_control WHERE name =
'find_cells_mult_update') AND (NEW."geom" NOT NULL AND NOT
ST_IsEmpty(NEW."geom"))
    BEGIN
        DELETE FROM "mult_cells" WHERE area_fid = OLD."fid";
        INSERT INTO "mult_cells" (area_fid, grid_fid, wdr, dm, nodchns,
xnmult)
        SELECT NEW.fid, g.fid, NEW.wdr, NEW.dm, NEW.nodchns, NEW.xnmult
 FROM grid as g
        WHERE ST_Intersects(CastAutomagic(g.geom), CastAutomagic(NEW.geom));
    END;



Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DKaren** [comment]
I'm testing that right now.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

Mult areas only apply when someone imports a dataset.  They should export the same way they import.  So we don't want extra cells in the table compared to the MultAreas.
